{
 "title": "Race",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "race",
    "query": "SELECT id FROM races ORDER BY started_at DESC;"
   }
  ]
 },
 "panels": [
  {
   "title": "Track Name",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT tracks.name as \"Name\", tracks.layout as \"Layout\", tracks.length as \"Length\" FROM races LEFT JOIN tracks ON (tracks.ordinal = races.track) WHERE id = '$race'"
    }
   ]
  },
  {
   "title": "Track Layout",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 18 }
   ]
  },
  {
   "title": "Track Length",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 18 }
   ]
  },
  {
   "title": "Best Lap",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "time: m:ss.SSS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT best_lap * 1000 as \"Best Lap\", distance_traveled as \"Distance Travelled\", current_race_time * 1000 as \"Race Time\" FROM points WHERE race = '$race' ORDER BY created_at DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Distance Travelled",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Race Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "time: m:ss.SSS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Positon",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT race_position FROM points WHERE race = '$race' ORDER BY created_at DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Car Make",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cars.make as \"Make\", cars.model as \"Model\", cars.year as \"Year\", car_performance_index as \"PI\", car_class as \"Class\" FROM races LEFT JOIN cars ON (cars.ordinal = races.car) WHERE id = '$race'"
    }
   ]
  },
  {
   "title": "Car Model",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Car Year",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Car PI",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Car Class",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Lap Times",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT lap_number + 1 as \"Lap\", MAX(current_lap) * 1000 as \"Time\" FROM points WHERE race = '$race' GROUP BY lap_number ORDER BY lap_number"
    }
   ]
  },
  {
   "title": "Race position",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT created_at, race_position AS \"Position\" FROM points WHERE race = '$race' "
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "rawSql": "SELECT speed * 3.6 as \"Speed\", created_at FROM points WHERE race = '$race'"
    }
   ]
  },
  {
   "title": "Gear / RPM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "rawSql": "SELECT created_at, gear AS \"Gear\", engine_current_rpm AS \"RPM\" FROM points WHERE race = '$race' "
    }
   ]
  },
  {
   "title": "Acceleration / Braking",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT created_at, accel / 255.0 as \"Acceleration\", brake / 255.0 as \"Braking\" FROM points WHERE race = '$race'"
    }
   ]
  },
  {
   "title": "Tire Wear",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT created_at, tire_wear_front_left AS \"Front Left\", tire_wear_front_right AS \"Front Right\", tire_wear_rear_left AS \"Rear Left\", tire_wear_rear_right AS \"Rear Right\" FROM points WHERE race = '$race' "
    }
   ]
  },
  {
   "title": "Tire Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT created_at, (tire_temp_front_left - 32) * 5 / 9 AS \"Front Left\", (tire_temp_front_right  - 32) * 5 / 9 AS \"Front Right\", (tire_temp_rear_left  - 32) * 5 / 9 AS \"Rear Left\", (tire_temp_rear_right  - 32) * 5 / 9 AS \"Rear RIght\" FROM points WHERE race = '$race' "
    }
   ]
  },
  {
   "title": "Fuel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT created_at, fuel AS \"Fuel\" FROM points WHERE race = '$race' "
    }
   ]
  }
 ]
}