name: CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Build
        run: just build

      - name: Test
        run: just test

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

  Release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Publish dev
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: Latest build
          tag_name: dev
          files: build/x86_64/forzatelemetry
          fail_on_unmatched_files: true
