name: Generate

on:
  workflow_dispatch:
  schedule:
  # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * FRI'

jobs:
  Generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
            
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
                
      - name: Install just
        uses: extractions/setup-just@v2
                
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: '3.19.6'  # Fedora 41 version

      - name: Regenerate
        run: just generate
                
      - name: Build
        run: just build
                
      - name: Test
        run: just test

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: regenerate cars and tracks
          branch: auto/generate-cars-and-tracks
          delete-branch: true
          title: 'Regenerate cars and tracks'
          body: 'This is the PR with the updated cars and tracks metadata'
