// Code generated DO NOT EDIT.

package models

var Tracks = []Track{
	{
		Ordinal:  0,
		Name:     "WeatherTech Raceway Laguna Seca",
		Layout:   "Full Circuit",
		Location: "California",
		Length:   3.60,
	},
	{
		Ordinal:  1,
		Name:     "WeatherTech Raceway Laguna Seca",
		Layout:   "Short Circuit",
		Location: "California",
		Length:   2.96,
	},
	{
		Ordinal:  3,
		Name:     "Road America",
		Layout:   "Full Circuit",
		Location: "Wisconsin",
		Length:   6.52,
	},
	{
		Ordinal:  5,
		Name:     "Road America",
		Layout:   "East Route",
		Location: "Wisconsin",
		Length:   3.52,
	},
	{
		Ordinal:  16,
		Name:     "Road Atlanta",
		Layout:   "Full",
		Location: "Georgia",
		Length:   4.10,
	},
	{
		Ordinal:  17,
		Name:     "Road Atlanta",
		Layout:   "Club",
		Location: "Georgia",
		Length:   2.85,
	},
	{
		Ordinal:  21,
		Name:     "Silverstone Racing Circuit",
		Layout:   "Grand Prix Circuit",
		Location: "Silverston",
		Length:   5.89,
	},
	{
		Ordinal:  22,
		Name:     "Silverstone Racing Circuit",
		Layout:   "National Circuit",
		Location: "Silverston",
		Length:   2.64,
	},
	{
		Ordinal:  23,
		Name:     "Silverstone Racing Circuit",
		Layout:   "International Circuit",
		Location: "Silverston",
		Length:   2.98,
	},
	{
		Ordinal:  31,
		Name:     "Nürburgring",
		Layout:   "Full Circuit",
		Location: "Nürburg",
		Length:   25.38,
	},
	{
		Ordinal:  32,
		Name:     "Nürburgring",
		Layout:   "Nordschleife",
		Location: "Nürburg",
		Length:   20.83,
	},
	{
		Ordinal:  33,
		Name:     "Nürburgring",
		Layout:   "GP Circuit",
		Location: "Nürburg",
		Length:   5.15,
	},
	{
		Ordinal:  34,
		Name:     "Nürburgring",
		Layout:   "Sprint Circuit",
		Location: "Nürburg",
		Length:   3.63,
	},
	{
		Ordinal:  35,
		Name:     "Mugello Circuit",
		Layout:   "Full Circuit",
		Location: "Tuscany",
		Length:   5.25,
	},
	{
		Ordinal:  36,
		Name:     "Mugello Circuit",
		Layout:   "Club Circuit",
		Location: "Tuscany",
		Length:   2.58,
	},
	{
		Ordinal:  37,
		Name:     "Suzuka Circuit",
		Layout:   "Full Circuit",
		Location: "Suzuka",
		Length:   5.81,
	},
	{
		Ordinal:  38,
		Name:     "Suzuka Circuit",
		Layout:   "East Circuit",
		Location: "Suzuka",
		Length:   2.25,
	},
	{
		Ordinal:  40,
		Name:     "Sebring International",
		Layout:   "Full",
		Location: "Sebring",
		Length:   6.02,
	},
	{
		Ordinal:  42,
		Name:     "Sebring International",
		Layout:   "Short",
		Location: "Sebring",
		Length:   3.54,
	},
	{
		Ordinal:  67,
		Name:     "Maple Valley",
		Layout:   "Full Circuit",
		Location: "Vermont",
		Length:   4.81,
	},
	{
		Ordinal:  68,
		Name:     "Maple Valley",
		Layout:   "Short Circuit",
		Location: "Vermont",
		Length:   1.85,
	},
	{
		Ordinal:  70,
		Name:     "Maple Valley",
		Layout:   "Short Circuit Reverse",
		Location: "Vermont",
		Length:   1.85,
	},
	{
		Ordinal:  78,
		Name:     "Fujimi Kaido",
		Layout:   "Full",
		Location: "Japan",
		Length:   16.42,
	},
	{
		Ordinal:  83,
		Name:     "Fujimi Kaido",
		Layout:   "Full Reverse",
		Location: "Japan",
		Length:   16.42,
	},
	{
		Ordinal:  100,
		Name:     "Le Mans - Circuit International de la Sarthe",
		Layout:   "Full Circuit",
		Location: "Le Mans",
		Length:   13.63,
	},
	{
		Ordinal:  101,
		Name:     "Le Mans - Circuit International de la Sarthe",
		Layout:   "Old Mulsanne Circuit",
		Location: "Le Mans",
		Length:   13.54,
	},
	{
		Ordinal:  110,
		Name:     "Circuit de Barcelona-Catalunya",
		Layout:   "Grand Prix Circuit",
		Location: "Barcelona",
		Length:   4.66,
	},
	{
		Ordinal:  111,
		Name:     "Circuit de Barcelona-Catalunya",
		Layout:   "National Circuit",
		Location: "Barcelona",
		Length:   3.07,
	},
	{
		Ordinal:  113,
		Name:     "Circuit de Barcelona-Catalunya",
		Layout:   "National Circuit Alt",
		Location: "Barcelona",
		Length:   3.00,
	},
	{
		Ordinal:  231,
		Name:     "Indianapolis Motor Speedway",
		Layout:   "The Brickyard Speedway",
		Location: "Indianapolis",
		Length:   4.02,
	},
	{
		Ordinal:  232,
		Name:     "Indianapolis Motor Speedway",
		Layout:   "Grand Prix Circuit",
		Location: "Indianapolis",
		Length:   3.93,
	},
	{
		Ordinal:  250,
		Name:     "Hockenheimring",
		Layout:   "Full Circuit",
		Location: "Hockenheim",
		Length:   4.57,
	},
	{
		Ordinal:  251,
		Name:     "Hockenheimring",
		Layout:   "National Circuit",
		Location: "Hockenheim",
		Length:   3.69,
	},
	{
		Ordinal:  252,
		Name:     "Hockenheimring",
		Layout:   "Short Circuit",
		Location: "Hockenheim",
		Length:   2.64,
	},
	{
		Ordinal:  510,
		Name:     "Yas Marina Circuit",
		Layout:   "Full Circuit",
		Location: "Abu Dhabi",
		Length:   5.28,
	},
	{
		Ordinal:  511,
		Name:     "Yas Marina Circuit",
		Layout:   "North Circuit",
		Location: "Abu Dhabi",
		Length:   3.00,
	},
	{
		Ordinal:  512,
		Name:     "Yas Marina Circuit",
		Layout:   "South Circuit",
		Location: "Abu Dhabi",
		Length:   2.19,
	},
	{
		Ordinal:  513,
		Name:     "Yas Marina Circuit",
		Layout:   "North Corkscrew",
		Location: "Abu Dhabi",
		Length:   2.29,
	},
	{
		Ordinal:  530,
		Name:     "Circuit de Spa-Francorchamps",
		Layout:   "Full Circuit",
		Location: "Spa",
		Length:   7.00,
	},
	{
		Ordinal:  540,
		Name:     "Mount Panorama",
		Layout:   "Circuit",
		Location: "Australia",
		Length:   6.21,
	},
	{
		Ordinal:  840,
		Name:     "Daytona Intl Speedway",
		Layout:   "Sports Car Circuit",
		Location: "Daytona",
		Length:   5.78,
	},
	{
		Ordinal:  841,
		Name:     "Daytona Intl Speedway",
		Layout:   "Tri-Oval Circuit",
		Location: "Daytona",
		Length:   4.02,
	},
	{
		Ordinal:  860,
		Name:     "Brand Hatch",
		Layout:   "Tor Grand Prix",
		Location: "West Kingsdown",
		Length:   3.70,
	},
	{
		Ordinal:  861,
		Name:     "Brand Hatch",
		Layout:   "Tor Indy",
		Location: "West Kingsdown",
		Length:   1.93,
	},
	{
		Ordinal:  870,
		Name:     "Watkins Glen International Speedway",
		Layout:   "Full Circuit",
		Location: "New York",
		Length:   5.55,
	},
	{
		Ordinal:  873,
		Name:     "Watkins Glen International Speedway",
		Layout:   "Short Circuit",
		Location: "New York",
		Length:   3.94,
	},
	{
		Ordinal:  880,
		Name:     "Lime Rock Park",
		Layout:   "Full Circuit",
		Location: "Connecticut",
		Length:   2.41,
	},
	{
		Ordinal:  882,
		Name:     "Lime Rock Park",
		Layout:   "South Chicane",
		Location: "Connecticut",
		Length:   2.37,
	},
	{
		Ordinal:  883,
		Name:     "Lime Rock Park",
		Layout:   "Full Circuit Alt",
		Location: "Connecticut",
		Length:   2.41,
	},
	{
		Ordinal:  990,
		Name:     "Virginia International Raceway",
		Layout:   "Full",
		Location: "Virginia",
		Length:   5.26,
	},
	{
		Ordinal:  991,
		Name:     "Virginia International Raceway",
		Layout:   "North",
		Location: "Virginia",
		Length:   3.62,
	},
	{
		Ordinal:  992,
		Name:     "Virginia International Raceway",
		Layout:   "South",
		Location: "Virginia",
		Length:   2.66,
	},
	{
		Ordinal:  995,
		Name:     "Virginia International Raceway",
		Layout:   "Grand West",
		Location: "Virginia",
		Length:   6.60,
	},
	{
		Ordinal:  996,
		Name:     "Virginia International Raceway",
		Layout:   "Grand East",
		Location: "Virginia",
		Length:   6.76,
	},
	{
		Ordinal:  1110,
		Name:     "Homestead-Miami Speedway",
		Layout:   "Speedway Circuit",
		Location: "Florida",
		Length:   2.41,
	},
	{
		Ordinal:  1111,
		Name:     "Homestead-Miami Speedway",
		Layout:   "Road Circuit",
		Location: "Florida",
		Length:   3.56,
	},
	{
		Ordinal:  1450,
		Name:     "Mid-Ohio Sports Car Course",
		Layout:   "Full Circuit",
		Location: "Ohio",
		Length:   3.62,
	},
	{
		Ordinal:  1452,
		Name:     "Mid-Ohio Sports Car Course",
		Layout:   "Short Circuit",
		Location: "Ohio",
		Length:   2.82,
	},
	{
		Ordinal:  1590,
		Name:     "Kyalami Grand Prix Circuit",
		Layout:   "Grand Prix Circuit",
		Location: "Midrand",
		Length:   4.53,
	},
	{
		Ordinal:  1620,
		Name:     "Sunset Peninsula Raceway",
		Layout:   "Full",
		Location: "Florida",
		Length:   4.47,
	},
	{
		Ordinal:  1621,
		Name:     "Sunset Peninsula Raceway",
		Layout:   "Club",
		Location: "Florida",
		Length:   3.12,
	},
	{
		Ordinal:  1622,
		Name:     "Sunset Peninsula Raceway",
		Layout:   "Full Reverse",
		Location: "Florida",
		Length:   4.47,
	},
	{
		Ordinal:  1623,
		Name:     "Sunset Peninsula Raceway",
		Layout:   "Club Reverse",
		Location: "Florida",
		Length:   3.12,
	},
	{
		Ordinal:  1624,
		Name:     "Sunset Peninsula Raceway",
		Layout:   "Speedway",
		Location: "Florida",
		Length:   3.93,
	},
	{
		Ordinal:  1630,
		Name:     "Grand Oak Raceway",
		Layout:   "National Circuit",
		Location: "New Hampshire",
		Length:   3.73,
	},
	{
		Ordinal:  1631,
		Name:     "Grand Oak Raceway",
		Layout:   "Club Circuit",
		Location: "New Hampshire",
		Length:   2.62,
	},
	{
		Ordinal:  1632,
		Name:     "Grand Oak Raceway",
		Layout:   "National Circuit Reverse",
		Location: "New Hampshire",
		Length:   3.73,
	},
	{
		Ordinal:  1640,
		Name:     "Hakone",
		Layout:   "Grand Prix Circuit",
		Location: "Hakone",
		Length:   4.28,
	},
	{
		Ordinal:  1641,
		Name:     "Hakone",
		Layout:   "Club Circuit",
		Location: "Hakone",
		Length:   3.32,
	},
	{
		Ordinal:  1643,
		Name:     "Hakone",
		Layout:   "Club Circuit Reverse",
		Location: "Hakone",
		Length:   3.32,
	},
	{
		Ordinal:  1660,
		Name:     "Eaglerock Speedway",
		Layout:   "Oval Circuit",
		Location: "Iowa",
		Length:   1.64,
	},
	{
		Ordinal:  1661,
		Name:     "Eaglerock Speedway",
		Layout:   "Club Circuit",
		Location: "Iowa",
		Length:   1.72,
	},
	{
		Ordinal:  1663,
		Name:     "Eaglerock Speedway",
		Layout:   "Club Circuit Reverse",
		Location: "Iowa",
		Length:   1.72,
	},
}
